### ISSUE TITLE
Satellite image missing

### ISSUE THREAD

**Issue by cskda** [chadrockey/TGC-Designer-Tools#118] opened 2023-02-04 03:44 UTC
![5881616A-BE8D-43A2-8ECF-16DFDA98E9C8](https://user-images.githubusercontent.com/124405426/216746083-2bc628ab-5077-43fa-a327-64ca18861141.jpeg)
The OSM image doesn’t show up when I try to use it

**Comment by chadrockey** [comment] 2023-02-04 03:45
Duplicate of #115

**Closed by chadrockey** 2023-02-04 03:45 UTC
