### ISSUE TITLE
Importing directly into PGA Tour 2K21

### ISSUE THREAD

**Issue by UnderDogg** [chadrockey/TGC-Designer-Tools#57] opened 2020-08-30 14:04 UTC
hey @chadrockey,
The tool works flawlessly, but I (we) would be very grateful if we could import these files directly into PGA Tour 2K21.

Can you let us know when (if) you would work on that?

I'll be happy to beta-test.

**Comment by chadrockey** [comment] 2020-09-14 21:46
I don't own a copy of 2K21 and don't plan on updating at this time.  PR are highly welcome though!

Duplicate of #55

**Closed by chadrockey** 2020-09-14 21:46 UTC
